version: "3"
services:
  face:
    build: ../faceReconnation/
    image: faucon04/face
    ports:
      - "5000:5000"

  auth:
    build: ../auth/
    image: faucon04/auth
    ports:
      - "3002:3002"
    networks:
      - gatewaynetwork

  gateway:
    build: ../gateway/
    image: faucon04/gateway
    ports:
      - "4000:4000"
    depends_on:
      - face
      - auth
    environment:
      AUTH_SUBGRAPH: http://auth:3002/query
    networks:
      - gatewaynetwork

  front:
    build: ../render/
    image: faucon04/front
    ports:
      - "4200:4200"
    depends_on:
      - gateway


networks:
  gatewaynetwork:
    driver: bridge